# Generated by Django 3.2.3 on 2024-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ad_id', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
    ]
